### ISSUE TITLE
Cannot run parallel jobs

### ISSUE THREAD

**Issue by Jigyasa3** [timkahlke/BASTA#24]
Hey @timkahlke 

I am working with multiple metagenome taxonomy, and I was wondering if it's possible to parallelize the job?

When I try to do so, I get an error even though I am using different databases for two different runs-

Traceback (most recent call last):
  File "/work/student/jigyasa-arora/BASTA-1.3.2.3/bin/basta", line 115, in <module>
    main.run_basta(args)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/BastaMain.py", line 80, in run_basta
    self._basta_multiple(args)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/BastaMain.py", line 121, in _basta_multiple
    assigner._assign_multiple(args.blast,db_file,args.best_hit)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/AssignTaxonomy.py", line 101, in _assign_multiple
    lca = self._assign_single(os.path.join(blast_dir,bf),db_file,best)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/AssignTaxonomy.py", line 79, in _assign_single
    (tax_lookup, map_lookup) = self._get_lookups(db_file)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/AssignTaxonomy.py", line 108, in _get_lookups
    tax_lookup = db._init_db(os.path.join(self.directory,"complete_taxa.db"))
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/DBUtils.py", line 75, in _init_db
    lookup = plyvel.DB(os.path.abspath(db))
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: IO error: lock /home/j/jigyasa-arora/.basta/taxonomy/complete_taxa.db/LOCK: Resource temporarily unavailable

**Comment by timkahlke** [comment]
Hi @Jigyasa3 

Sorry, there might be a solution but I won't have time atm to put it in.

One quick and very dirty solution would be to copy BASTA's complete "taxonomy" folder into another directory and then set the taxonomy directory using the "-p" option. However, this will mean you'd need one directory per BASTA run ... not sure if that's actually usefull for you.
